server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sganalyzer?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: junaid@_1013

  jpa:
    hibernate:
      ddl-auto: update   # keep schema updated without wiping data
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      mode: always
      continue-on-error: true

logging:
  level:
    org.hibernate.SQL: warn

ai:
  api:
    key: "AIzaSyCDODjsWdUQAmG0F9o01yycnNp8LlG827c"
    url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"

